<?php
// Copyright (c) 2026 Diego Montoya
// SPDX-License-Identifier: AGPL-3.0

declare(strict_types=1);

namespace Cofacture\Builder;

use Cofacture\Builder\Internal\PartyXmlBuilder;
use Cofacture\Domain\Event;
use Cofacture\Domain\EventDocumentReference;
use Cofacture\Domain\EventParty;
use Cofacture\Domain\EventReceiverPerson;
use Cofacture\Domain\Reclamo;
use Cofacture\Event\Event as EventCude;
use Cofacture\Xml\El;
use Cofacture\Xml\Namespaces as NS;
use DOMDocument;
use DOMElement;
use InvalidArgumentException;

/**
 * Builds the 5 RADIAN event documents (ApplicationResponse): Acuse de Recibo, Reclamo, Recibo
 * del Bien, Aceptación Expresa, Aceptación Tácita. Mirrors builder/event.go.
 *
 * NOTE ON VERIFICATION: unlike every other builder in this port, the structure here was
 * assembled from the Technical Annex's field tables (section 6.5.4/6.5.5, Resolución
 * 000165/2023) and the standard UBL 2.1 ApplicationResponse schema — it has not been
 * cross-checked against a real, DIAN-accepted event document the way InvoiceBuilder/
 * SupportDocumentBuilder/etc. were. Treat it as "should be correct per the annex text" rather
 * than "verified", and confirm against the certification (habilitación) environment before
 * relying on it in production. Same caveat as the Go original.
 */
final class EventBuilder
{
    private const CUSTOMIZATION_ID = '1';
    private const PROFILE_ID = 'DIAN 2.1: ApplicationResponse de Factura Electrónica de Venta';

    private function __construct()
    {
    }

    /**
     * Builds the "Acuse de Recibo de la Factura Electrónica de Venta" event (responseCode
     * "030", section 6.5.5.3) — the acquirer's acknowledgment that it received the document.
     * $ev->receiverPerson is required: DIAN mandates identifying the natural person who received
     * it (cac:DocumentResponse/cac:IssuerParty/cac:Person).
     */
    public static function buildAcuseRecibo(Event $ev): DOMDocument
    {
        if ($ev->receiverPerson === null) {
            throw new InvalidArgumentException('builder: Acuse de Recibo requires $ev->receiverPerson');
        }
        $doc = self::buildEventSkeleton($ev);
        $dr = self::appendDocumentResponse($doc->documentElement, EventCude::RESPONSE_CODE_ACUSE_RECIBO, 'Acuse de recibo de Factura Electrónica de Venta', '', '', $ev->documentReference);
        self::appendEventIssuerParty($dr, $ev->receiverPerson);
        return $doc;
    }

    /** Builds the "Recibo del Bien y/o Prestación del Servicio" event (responseCode "032",
     *  section 6.5.5.5). */
    public static function buildRecibidoBien(Event $ev): DOMDocument
    {
        $doc = self::buildEventSkeleton($ev);
        self::appendDocumentResponse($doc->documentElement, EventCude::RESPONSE_CODE_RECIBIDO_BIEN, 'Recibo del bien y/o prestación del servicio', '', '', $ev->documentReference);
        return $doc;
    }

    /** Builds the "Aceptación Expresa" event (responseCode "033", section 6.5.5.6) — the
     *  acquirer's explicit acceptance of the document. */
    public static function buildAceptacionExpresa(Event $ev): DOMDocument
    {
        $doc = self::buildEventSkeleton($ev);
        self::appendDocumentResponse($doc->documentElement, EventCude::RESPONSE_CODE_ACEPTACION_EXPRESA, 'Aceptación expresa', '', '', $ev->documentReference);
        return $doc;
    }

    /**
     * Builds the "Aceptación Tácita" event (responseCode "034", section 6.5.5.7). Unlike every
     * other event, this one is generated by the ISSUER (not the acquirer) and sent to DIAN once
     * 3 business days have passed since Recibo del Bien with no explicit acceptance or claim —
     * DIAN requires $ev->note to carry a specific sworn-statement template; see
     * Event\Event::tacitAcceptanceNote() to build it correctly instead of writing it by hand.
     */
    public static function buildAceptacionTacita(Event $ev): DOMDocument
    {
        $doc = self::buildEventSkeleton($ev);
        self::appendDocumentResponse($doc->documentElement, EventCude::RESPONSE_CODE_ACEPTACION_TACITA, 'Aceptación Tácita', '', '', $ev->documentReference);
        return $doc;
    }

    /**
     * Builds the "Reclamo de la Factura Electrónica de Venta" event (responseCode "031",
     * section 6.5.5.4) — the acquirer's rejection of the document on commercial grounds.
     * $r->rejectionListId/$r->rejectionName carry the rejection reason from DIAN's catalog
     * (section 13.3.11); this library does not validate them, same boundary as
     * DiscrepancyResponse.
     */
    public static function buildReclamo(Reclamo $r): DOMDocument
    {
        $doc = self::buildEventSkeleton($r);
        self::appendDocumentResponse($doc->documentElement, EventCude::RESPONSE_CODE_RECLAMO, 'Reclamo de la Factura Electrónica de Venta', $r->rejectionListId, $r->rejectionName, $r->documentReference);
        return $doc;
    }

    /** Builds everything every event shares: namespaces, DIAN extensions, header fields, and
     *  Sender/ReceiverParty. Callers append their own cac:DocumentResponse. */
    private static function buildEventSkeleton(Event $ev): DOMDocument
    {
        $doc = new DOMDocument('1.0', 'UTF-8');
        $doc->xmlStandalone = false;

        $root = $doc->createElementNS(NS::NS_APPLICATION_RESPONSE, 'ApplicationResponse');
        $doc->appendChild($root);
        El::declareNamespace($root, '', NS::NS_APPLICATION_RESPONSE);
        El::declareNamespace($root, 'cac', NS::NS_CAC);
        El::declareNamespace($root, 'cbc', NS::NS_CBC);
        El::declareNamespace($root, 'ds', NS::NS_DS);
        El::declareNamespace($root, 'ext', NS::NS_EXT);
        El::declareNamespace($root, 'sts', NS::NS_STS);
        El::declareNamespace($root, 'xades', NS::NS_XADES);
        El::declareNamespace($root, 'xades141', NS::NS_XADES141);
        El::declareNamespace($root, 'xsi', NS::NS_XSI);
        $root->setAttributeNS(NS::NS_XSI, 'xsi:schemaLocation', NS::SCHEMA_LOCATION_APPLICATION_RESPONSE);

        self::appendEventUblExtensions($root, $ev);

        $root->appendChild(El::create($doc, 'cbc:UBLVersionID', 'UBL 2.1'));
        $root->appendChild(El::create($doc, 'cbc:CustomizationID', self::CUSTOMIZATION_ID));
        $root->appendChild(El::create($doc, 'cbc:ProfileID', self::PROFILE_ID));
        $root->appendChild(El::create($doc, 'cbc:ProfileExecutionID', $ev->environmentCode));
        $root->appendChild(El::create($doc, 'cbc:ID', $ev->id));

        $uuid = El::create($doc, 'cbc:UUID', $ev->cude);
        $root->appendChild($uuid);
        $uuid->setAttribute('schemeID', $ev->environmentCode);
        $uuid->setAttribute('schemeName', 'CUDE-SHA384');

        $root->appendChild(El::create($doc, 'cbc:IssueDate', $ev->issueDate));
        $root->appendChild(El::create($doc, 'cbc:IssueTime', $ev->issueTime));
        if ($ev->note !== '') {
            $root->appendChild(El::create($doc, 'cbc:Note', $ev->note));
        }

        self::appendEventParty($root, 'SenderParty', $ev->sender);
        self::appendEventParty($root, 'ReceiverParty', $ev->receiver);

        return $doc;
    }

    /**
     * Mirrors ExtensionsXmlBuilder::appendUBLExtensions() — same DIAN extension blocks
     * (InvoiceSource, SoftwareProvider, SoftwareSecurityCode, AuthorizationProvider, QRCode) —
     * except events have no sts:InvoiceControl (that group only applies to documents with their
     * own DIAN numbering resolution: Invoice and Support Document).
     */
    private static function appendEventUblExtensions(DOMElement $parent, Event $ev): void
    {
        $doc = $parent->ownerDocument;
        $extensions = El::create($doc, 'ext:UBLExtensions');
        $parent->appendChild($extensions);

        $firstExtension = El::create($doc, 'ext:UBLExtension');
        $extensions->appendChild($firstExtension);
        $extensionContent = El::create($doc, 'ext:ExtensionContent');
        $firstExtension->appendChild($extensionContent);
        $dianExt = El::create($doc, 'sts:DianExtensions');
        $extensionContent->appendChild($dianExt);

        $invoiceSource = El::create($doc, 'sts:InvoiceSource');
        $dianExt->appendChild($invoiceSource);
        $source = El::create($doc, 'cbc:IdentificationCode', 'CO');
        $invoiceSource->appendChild($source);
        $source->setAttribute('listAgencyID', '6');
        $source->setAttribute('listAgencyName', 'United Nations Economic Commission for Europe');
        $source->setAttribute('listSchemeURI', 'urn:oasis:names:specification:ubl:codelist:gc:CountryIdentificationCode-2.1');

        $swProvider = El::create($doc, 'sts:SoftwareProvider');
        $dianExt->appendChild($swProvider);
        $providerId = El::create($doc, 'sts:ProviderID', $ev->softwareProvider->providerIdentification->number);
        $swProvider->appendChild($providerId);
        $providerId->setAttribute('schemeAgencyID', NS::DIAN_SCHEME_AGENCY_ID);
        $providerId->setAttribute('schemeAgencyName', NS::DIAN_SCHEME_AGENCY_NAME);
        if ($ev->softwareProvider->providerIdentification->typeCode === NS::IDENTIFICATION_TYPE_NIT) {
            $providerId->setAttribute('schemeID', $ev->softwareProvider->providerIdentification->verificationCode);
        }
        $providerId->setAttribute('schemeName', $ev->softwareProvider->providerIdentification->typeCode);

        $softwareId = El::create($doc, 'sts:SoftwareID', $ev->softwareProvider->softwareId);
        $swProvider->appendChild($softwareId);
        $softwareId->setAttribute('schemeAgencyID', NS::DIAN_SCHEME_AGENCY_ID);
        $softwareId->setAttribute('schemeAgencyName', NS::DIAN_SCHEME_AGENCY_NAME);

        $secCode = El::create($doc, 'sts:SoftwareSecurityCode', $ev->softwareSecurityCode);
        $dianExt->appendChild($secCode);
        $secCode->setAttribute('schemeAgencyID', NS::DIAN_SCHEME_AGENCY_ID);
        $secCode->setAttribute('schemeAgencyName', NS::DIAN_SCHEME_AGENCY_NAME);

        $authProvider = El::create($doc, 'sts:AuthorizationProvider');
        $dianExt->appendChild($authProvider);
        $authProviderId = El::create($doc, 'sts:AuthorizationProviderID', NS::DIAN_AUTHORIZATION_PROVIDER_ID);
        $authProvider->appendChild($authProviderId);
        $authProviderId->setAttribute('schemeAgencyID', NS::DIAN_SCHEME_AGENCY_ID);
        $authProviderId->setAttribute('schemeAgencyName', NS::DIAN_SCHEME_AGENCY_NAME);
        $authProviderId->setAttribute('schemeID', '4');
        $authProviderId->setAttribute('schemeName', '31');

        $dianExt->appendChild(El::create($doc, 'sts:QRCode', $ev->qrUrl));

        // Reserved for the XAdES signature (Signer::sign() fills it in later).
        $secondExtension = El::create($doc, 'ext:UBLExtension');
        $extensions->appendChild($secondExtension);
        $secondExtension->appendChild(El::create($doc, 'ext:ExtensionContent'));
    }

    /**
     * Appends cac:SenderParty or cac:ReceiverParty (section 6.5.4, groups AAF/AAG) — a narrower
     * shape than PartyXmlBuilder::appendAccountingParty(): just PartyTaxScheme, no
     * PartyIdentification, PhysicalLocation, PartyLegalEntity or Contact.
     */
    private static function appendEventParty(DOMElement $parent, string $node, EventParty $p): void
    {
        $doc = $parent->ownerDocument;
        $party = El::create($doc, 'cac:' . $node);
        $parent->appendChild($party);
        $taxScheme = El::create($doc, 'cac:PartyTaxScheme');
        $party->appendChild($taxScheme);
        $taxScheme->appendChild(El::create($doc, 'cbc:RegistrationName', $p->name));
        $companyId = El::create($doc, 'cbc:CompanyID', $p->identification->number);
        $taxScheme->appendChild($companyId);
        PartyXmlBuilder::setIdentificationAttrs($companyId, $p->identification);
        $scheme = El::create($doc, 'cac:TaxScheme');
        $taxScheme->appendChild($scheme);
        $scheme->appendChild(El::create($doc, 'cbc:ID', $p->taxSchemeCode));
        $scheme->appendChild(El::create($doc, 'cbc:Name', $p->taxSchemeName));
    }

    /**
     * Appends cac:DocumentResponse (section 6.5.5, groups AAH01-09): the event code/description
     * and the reference to the document it applies to. $rejectionListId/$rejectionName are only
     * non-empty for Reclamo — they become cbc:ResponseCode's @listID/@name attributes; every
     * other event omits both. Returns the cac:DocumentResponse element so callers that need to
     * append more to it (Acuse de Recibo's IssuerParty) can.
     */
    private static function appendDocumentResponse(
        DOMElement $parent,
        string $responseCode,
        string $description,
        string $rejectionListId,
        string $rejectionName,
        EventDocumentReference $ref,
    ): DOMElement {
        $doc = $parent->ownerDocument;
        $dr = El::create($doc, 'cac:DocumentResponse');
        $parent->appendChild($dr);
        $resp = El::create($doc, 'cac:Response');
        $dr->appendChild($resp);
        $rc = El::create($doc, 'cbc:ResponseCode', $responseCode);
        if ($rejectionListId !== '') {
            $rc->setAttribute('listID', $rejectionListId);
        }
        if ($rejectionName !== '') {
            $rc->setAttribute('name', $rejectionName);
        }
        $resp->appendChild($rc);
        $resp->appendChild(El::create($doc, 'cbc:Description', $description));

        $docRef = El::create($doc, 'cac:DocumentReference');
        $dr->appendChild($docRef);
        $docRef->appendChild(El::create($doc, 'cbc:ID', $ref->prefix . $ref->number));
        $uuid = El::create($doc, 'cbc:UUID', $ref->cufe);
        $docRef->appendChild($uuid);
        $uuid->setAttribute('schemeName', $ref->hashType);
        $docRef->appendChild(El::create($doc, 'cbc:DocumentTypeCode', $ref->documentTypeCode));

        return $dr;
    }

    /**
     * Appends cac:DocumentResponse/cac:IssuerParty/cac:Person (section 6.5.5.3, groups
     * AAH11-18) — identifies the natural person who received the goods/service, required only
     * for Acuse de Recibo.
     */
    private static function appendEventIssuerParty(DOMElement $dr, EventReceiverPerson $p): void
    {
        $doc = $dr->ownerDocument;
        $issuerParty = El::create($doc, 'cac:IssuerParty');
        $dr->appendChild($issuerParty);
        $person = El::create($doc, 'cac:Person');
        $issuerParty->appendChild($person);
        $id = El::create($doc, 'cbc:ID', $p->identification->number);
        $person->appendChild($id);
        PartyXmlBuilder::setIdentificationAttrs($id, $p->identification);
        $person->appendChild(El::create($doc, 'cbc:FirstName', $p->firstName));
        $person->appendChild(El::create($doc, 'cbc:FamilyName', $p->familyName));
        if ($p->jobTitle !== '') {
            $person->appendChild(El::create($doc, 'cbc:JobTitle', $p->jobTitle));
        }
        if ($p->organizationDepartment !== '') {
            $person->appendChild(El::create($doc, 'cbc:OrganizationDepartment', $p->organizationDepartment));
        }
    }
}
